project_id = "xeqzpsejalqyzpqwtnpb"

[functions.stock-change-notification]
verify_jwt = false

[functions.parse-product-text]
verify_jwt = false

[functions.fetch-product-image]
verify_jwt = false

[functions.newsletter-notification]
verify_jwt = false
